spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      generate-ddl: false
    defer-datasource-initialization: true
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL-USERNAME}
    password: ${EMAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.3
          starttls:
            enable: true
            required: true

    auth-exp: ${AUTH-CODE-EXP}
    suffix: '${MAIL-SUFFIX}'

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

socket:
  port: 8081

redis:
  port: ${REDIS-PORT}
  host: ${REDIS-HOST}

jwt:
  header: ${HEADER}
  prefix : ${PREFIX}
  secret-key: ${JWT-SECRET}
  access-exp: ${ACCESS-EXP}
  refresh-exp: ${REFRESH-EXP}

auth:
  google:
    base-url: ${GOOGLE-BASE-URL}
    client-id: ${GOOGLE-CLIENT-ID}
    client-secret: ${GOOGLE-SECRET}
    redirect-url: ${GOOGLE-REDIRECT-URL}

sentry:
  dsn: ${SENTRY-DSN}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
