name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: build docker image
        run: docker build -t rolls .

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker Build
         run: docker build -t ${{secrets.DOCKER_REPOSITORY}} .

      - name: Push on Dockerhub
          run: docker push ${{secrets.DOCKER_REPOSITORY}}

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: Docker run
        run: |
          sudo docker stop $(docker ps -a -q  --filter ancestor=${{secrets.DOCKER_REPOSITORY}})
          sudo nohup docker run --env-file ./my_env -p 8080:8080 ${{secrets.DOCKER_REPOSITORY}} &